require('dotenv').config()
const mongoose=require('mongoose')
const express=require('express')
const cors=require('cors')
const app=express()
const port=3050
app.use(express.json())
app.use(cors())
const {checkSchema}=require('express-validator')
const configDB=require('./config/db')
configDB()
const userValidationSchema=require('./app/validators/userValidations')
const userCtrlr=require('./app/controllers/otpGenerateController')
const otpValidateCtrlr=require('./app/controllers/otpValidateController')
app.post('/api/otpGenerate',checkSchema(userValidationSchema),userCtrlr.otpGenerate)
app.post('/api/otpValidate',otpValidateCtrlr.validate)
app.listen(port,()=>{
console.log(`server started succesfully on the port ${port}`)
})